name: COVID_MODEL
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - ca-certificates=2020.1.1=0
  - certifi=2020.4.5.1=py37_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - ncurses=6.2=he6710b0_0
  - openssl=1.1.1f=h7b6447c_0
  - pip=10.0.1=py37_0
  - python=3.7.7=hcf32534_0_cpython
  - readline=8.0=h7b6447c_0
  - setuptools=46.1.3=py37_0
  - sqlite=3.31.1=h7b6447c_0
  - tk=8.6.8=hbc83047_0
  - wheel=0.34.2=py37_0
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - pip:
    - attrs==19.3.0
    - backcall==0.1.0
    - bleach==3.1.4
    - cycler==0.10.0
    - datetime==4.3
    - decorator==4.4.2
    - defusedxml==0.6.0
    - entrypoints==0.3
    - importlib-metadata==1.6.0
    - ipykernel==5.2.1
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jedi==0.17.0
    - jinja2==2.11.2
    - jsonschema==3.2.0
    - jupyter-client==6.1.3
    - jupyter-core==4.6.3
    - kiwisolver==1.2.0
    - markupsafe==1.1.1
    - matplotlib==3.2.1
    - mistune==0.8.4
    - nbconvert==5.6.1
    - nbformat==5.0.6
    - networkx==2.4
    - notebook==6.0.3
    - numpy==1.18.2
    - pandas==1.0.3
    - pandocfilters==1.4.2
    - parso==0.7.0
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==3.0.5
    - ptyprocess==0.6.0
    - pygments==2.6.1
    - pyparsing==2.4.7
    - pyrsistent==0.16.0
    - python-dateutil==2.8.1
    - pytz==2019.3
    - pyzmq==19.0.0
    - scipy==1.4.1
    - send2trash==1.5.0
    - six==1.14.0
    - terminado==0.8.3
    - testpath==0.4.4
    - tornado==6.0.4
    - traitlets==4.3.3
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - widgetsnbextension==3.5.1
    - zipp==3.1.0
    - zope.interface==5.1.0
prefix: /home/bram/anaconda3/envs/COVID_MODEL

