name: COVID_MODEL
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - ipython
  - jupyter
  - notebook
  - matplotlib>3
  - numpy
  - scipy
  - xarray
  - networkx
  - pandas
  - ipywidgets
  - xlrd
  - pyMC3
  - theano
  - scikit-learn
  - openpyxl
  - emcee
