name: COVID_MODEL
channels:
  - defaults
  - conda-forge
dependencies:
  - pip
  - ipython
  - jupyter
  - notebook
  - matplotlib>3
  - numpy
  - scipy
  - xarray
  - networkx
  - pandas
  - ipywidgets
  - xlrd
  - scikit-learn
  - openpyxl
  - emcee
  - corner
  - geopandas
  - descartes
  - pyarrow
  - zarr
  - ujson
  - openpyxl
  - pyomo
  - numba
